### ISSUE TITLE
Turn off touch area / make area interactive.

### ISSUE THREAD

**Issue by djtango** [ArthurClemens/mithril-slider#2]
Hey this is really awesome, am just having a play around with this.

My use-case is to have a carousel of pages to cycle through (not sure if this is the most effective widget for this...!) but I notice that the touch area for swiping occupies the entire div - is there an option to turn this off? Just wanted to check before starting to play around with the internals...

**Comment by djtango** [comment]
Just to clarify, by interactive I mean highlightable text. links seem to work.

**Comment by ArthurClemens** [comment]
I don't think that the slider works well if you combine horizontal swiping with vertical scrollable content. In the examples is a 'Pages' example (not accessible in the menu) that shows the effect: http://arthurclemens.github.io/mithril-slider/index.html#/pages

If works ok-ish on desktop, but on mobile you see all kind of side effects because the scroll direction is not locked, and the browser has difficulties painting the image.
